import { User } from '@/models/user/user.entity';

export const usersMock: User[] = [
  {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    avatar: null,
    phone: '',
    role: 'user',
    createdAt: new Date('2024-09-09'),
    updatedAt: new Date('2024-09-09'),
  },
  {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    avatar: null,
    phone: '',
    role: 'user',
    createdAt: new Date('2024-08-08'),
    updatedAt: new Date('2024-08-08'),
  },
  {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    avatar: null,
    phone: '',
    role: 'user',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    avatar: null,
    phone: '',
    role: 'user',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: '',
    email: '',
    firstName: '',
    lastName: '',
    avatar: null,
    phone: '',
    role: 'user',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-10'),
  },
];
